### ISSUE TITLE
Importing of attachments and comments

### ISSUE THREAD

**Issue by nervgh** [yousefhamza/TrelloToYouTrack#3]
Hi

Nice job :+1: 

Please, add importing of attachments and comments of trello cards.

**Comment by yousefhamza** [comment]
Hey there!

It's cool that someone is using this!
I made it for personal use but just thought to make it public in case anyone wanted it!
I will continue working on it sure thing!
Hit me If you want any new features!

Thanks!

**Comment by nervgh** [comment]
Thanks :octocat:

**Comment by yousefhamza** [comment]
@nervgh I rewrote most of the thing and among other things I added comments and attachments, If u needed it again in the future 😅
